<a href="https://colab.research.google.com/github/MD2001/Pytorch_Bignnier/blob/main/00_pytoirch_first_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Title: 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Discussion forum: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## introduction
### tensors

In [2]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.shape

torch.Size([])

In [4]:
scaler.ndim

0

In [5]:
#Vector
Vector=torch.tensor([7,7])
Vector

tensor([7, 7])

In [6]:
Vector.shape

torch.Size([2])

In [7]:
Vector.ndim

1

In [8]:
#MATRIX
MATRIX =torch.tensor([[1,3],[2,4]])
MATRIX

tensor([[1, 3],
        [2, 4]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([1, 3])

In [12]:
MATRIX[1]

tensor([2, 4])

In [13]:
#Tensors
TENSOR = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 4])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [17]:
Tesnor2=torch.tensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
Tesnor2

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [18]:
Tesnor2.ndim

3

In [19]:
Tesnor2.shape

torch.Size([2, 3, 2])

## Random tensors
### Why random tensors?
### Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then
### Torch random tensors-https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
tensore_rand=torch.rand(3,4)
tensore_rand

tensor([[0.6216, 0.4021, 0.3021, 0.3254],
        [0.8195, 0.3274, 0.9559, 0.5192],
        [0.8246, 0.1910, 0.3819, 0.9650]])

In [21]:
tensore_rand2=torch.rand(size=(3,224,224))
tensore_rand2

tensor([[[0.1597, 0.7884, 0.7837,  ..., 0.2076, 0.3312, 0.0765],
         [0.0380, 0.2401, 0.9731,  ..., 0.3974, 0.3668, 0.4356],
         [0.1255, 0.4664, 0.6167,  ..., 0.0250, 0.6378, 0.6836],
         ...,
         [0.2760, 0.6852, 0.8285,  ..., 0.0081, 0.6784, 0.0887],
         [0.2647, 0.6092, 0.0090,  ..., 0.3375, 0.1681, 0.3273],
         [0.8377, 0.5787, 0.9644,  ..., 0.1628, 0.7750, 0.7449]],

        [[0.9646, 0.5656, 0.8725,  ..., 0.1098, 0.6162, 0.8611],
         [0.0552, 0.5560, 0.6498,  ..., 0.9505, 0.0571, 0.8631],
         [0.5582, 0.6312, 0.6366,  ..., 0.5389, 0.6499, 0.2737],
         ...,
         [0.8947, 0.1410, 0.5466,  ..., 0.6735, 0.0114, 0.6963],
         [0.2713, 0.2576, 0.1575,  ..., 0.0081, 0.0934, 0.6353],
         [0.3536, 0.4660, 0.5417,  ..., 0.4156, 0.6770, 0.0521]],

        [[0.3346, 0.7963, 0.6772,  ..., 0.1417, 0.5873, 0.3489],
         [0.0497, 0.7612, 0.4346,  ..., 0.5040, 0.0633, 0.4333],
         [0.6126, 0.0396, 0.4372,  ..., 0.2588, 0.3663, 0.

In [22]:
tensore_rand2.ndim , tensore_rand2.shape

(3, torch.Size([3, 224, 224]))

## zeros or ones arrays useed often to mask biger arrays

In [23]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
aranges=torch.arange(1,11,1)
aranges

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
zeros_like=torch.zeros_like(input=aranges)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch
& deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor*float_32_tensor ## why this work?

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor=torch.tensor([1,2,3],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
float_16_tensor*int_32_tensor

tensor([ 3., 12., 27.], dtype=torch.float16)

In [32]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.6775, 0.7792, 0.7232, 0.0187],
        [0.5518, 0.2100, 0.1968, 0.9648],
        [0.7054, 0.9073, 0.5390, 0.4065]])

In [33]:
print(some_tensor)
print(f"this is the dtype of tensor: {some_tensor.dtype}")
print(f"this is the shape of tenosr: {some_tensor.shape}")
print(f"this is the device of tensor: {some_tensor.device}")

tensor([[0.6775, 0.7792, 0.7232, 0.0187],
        [0.5518, 0.2100, 0.1968, 0.9648],
        [0.7054, 0.9073, 0.5390, 0.4065]])
this is the dtype of tensor: torch.float32
this is the shape of tenosr: torch.Size([3, 4])
this is the device of tensor: cpu


##math in tensors

In [34]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [35]:
tensor+10

tensor([11, 12, 13])

In [36]:
tensor*10

tensor([10, 20, 30])

In [37]:
tensor-10

tensor([-9, -8, -7])

In [38]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutliplication (dot product)
More information on multiplying matrices -  https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [39]:
%%time
torch.matmul(tensor,tensor)
## since the total time is 10 time or more less than for loop this method is too better

CPU times: user 0 ns, sys: 986 µs, total: 986 µs
Wall time: 14.5 ms


tensor(14)

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.43 ms, sys: 0 ns, total: 1.43 ms
Wall time: 1.46 ms


* short cut for torch.matmul is @
1. the first rule in matrxt multiblication is the inner dimintion should be equla
- for example:
* '(3,2)'@'(3,2)' not work
* '(3,2)'@'(2,3)' will work
* '(2,3)'@'(3,2)' will work
2. the resultin is the outer dimintion

In [41]:
(torch.rand(3,2) @ torch.rand(2,3) ).shape

torch.Size([3, 3])

#the transpose is importatint how to use it

In [42]:
tensor=torch.rand(3,2)
tensor

tensor([[0.4805, 0.3414],
        [0.3681, 0.2995],
        [0.3529, 0.7040]])

In [43]:
tensor @ tensor.T

tensor([[0.3474, 0.2791, 0.4099],
        [0.2791, 0.2252, 0.3407],
        [0.4099, 0.3407, 0.6201]])

In [44]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [46]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [47]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [49]:
x.argmax()

tensor(9)

In [50]:
x.argmin()

tensor(0)

##Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
View
* Return a view of an input tensor of certain shape but keep the same memory as the original tensor
Stacking
* combine multiple tensors on top of each other (vstack) or side by side (hstack)
Squeeze
* removes all 1 dimensions from a tensor
Unsqueeze
* add a 1 dimension to a target tensor
Permute
* Return a view of the input with dimensions permuted (swapped) in a certain way

In [52]:
tensor=torch.arange(1,10)
tensor,tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [57]:
tensor_reshape=tensor.reshape(1,9)
tensor_reshape,tensor_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [58]:
tensor_reshape=tensor.reshape(3,3)
tensor_reshape,tensor_reshape.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [59]:
tensor , tensor_reshape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [64]:
tensor[0]=66
tensor , tensor_reshape

(tensor([66,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[66,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

In [60]:
x=torch.arange(1,10)
x ,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [62]:
z=x.view(3,3)
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
x[0]=55
x,z
#reshape and view do the same

(tensor([55,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[55,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

**contiguous memore** : "each row follows the previous one directly in memory"
* view : contiguous it work fine but if not not work
* reshape : if not contiguous it rearnge it and work fine.

**then what make tensor not contiguous ??**

In [96]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
x = torch.stack((a, b))
x,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

the .stack() functions add two tensore together
* but using dim attribute behave like: "where the index of new diminshin will be"

  and this shape how the output will be

In [97]:
x = torch.stack((a, b),dim=0)
x,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [98]:
x = torch.stack((a, b),dim=1)
x,x.shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

### try higher diminshions

In [109]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
d = torch.randn(2, 3)
out = torch.stack((a, b, d), dim=0)
print(out,out.shape)
print("************************************************************************************************")
out = torch.stack((a, b, d), dim=1)
print(out,out.shape)
print("************************************************************************************************")
out = torch.stack((a, b, d), dim=2)
print(out,out.shape)
## the dim = 3 cuse error

tensor([[[-0.7721,  0.0875,  1.4551],
         [ 0.7687, -2.1235, -0.5734]],

        [[ 0.1822,  1.0570, -0.9065],
         [-0.7110, -0.1339,  0.0666]],

        [[-0.9552,  0.4038,  0.1224],
         [-0.0674,  0.8338,  0.2746]]]) torch.Size([3, 2, 3])
************************************************************************************************
tensor([[[-0.7721,  0.0875,  1.4551],
         [ 0.1822,  1.0570, -0.9065],
         [-0.9552,  0.4038,  0.1224]],

        [[ 0.7687, -2.1235, -0.5734],
         [-0.7110, -0.1339,  0.0666],
         [-0.0674,  0.8338,  0.2746]]]) torch.Size([2, 3, 3])
************************************************************************************************
tensor([[[-0.7721,  0.1822, -0.9552],
         [ 0.0875,  1.0570,  0.4038],
         [ 1.4551, -0.9065,  0.1224]],

        [[ 0.7687, -0.7110, -0.0674],
         [-2.1235, -0.1339,  0.8338],
         [-0.5734,  0.0666,  0.2746]]]) torch.Size([2, 3, 3])
