<a href="https://colab.research.google.com/github/MD2001/Pytorch_Bignnier/blob/main/00_pytoirch_first_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Title: 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Discussion forum: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## introduction
### tensors

In [2]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.shape

torch.Size([])

In [4]:
scaler.ndim

0

In [5]:
#Vector
Vector=torch.tensor([7,7])
Vector

tensor([7, 7])

In [6]:
Vector.shape

torch.Size([2])

In [7]:
Vector.ndim

1

In [8]:
#MATRIX
MATRIX =torch.tensor([[1,3],[2,4]])
MATRIX

tensor([[1, 3],
        [2, 4]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([1, 3])

In [12]:
MATRIX[1]

tensor([2, 4])

In [13]:
#Tensors
TENSOR = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 4])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [17]:
Tesnor2=torch.tensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
Tesnor2

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [18]:
Tesnor2.ndim

3

In [19]:
Tesnor2.shape

torch.Size([2, 3, 2])

## Random tensors
### Why random tensors?
### Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then
### Torch random tensors-https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
tensore_rand=torch.rand(3,4)
tensore_rand

tensor([[0.6973, 0.1848, 0.2394, 0.8562],
        [0.1613, 0.5661, 0.4597, 0.7260],
        [0.2411, 0.0914, 0.9587, 0.8112]])

In [21]:
tensore_rand2=torch.rand(size=(3,224,224))
tensore_rand2

tensor([[[0.4006, 0.9347, 0.6030,  ..., 0.3382, 0.1852, 0.0079],
         [0.3808, 0.0141, 0.3198,  ..., 0.8540, 0.0636, 0.3483],
         [0.5279, 0.0979, 0.5408,  ..., 0.1474, 0.4956, 0.7134],
         ...,
         [0.0719, 0.3899, 0.4326,  ..., 0.2124, 0.4217, 0.5050],
         [0.2712, 0.8000, 0.5662,  ..., 0.9608, 0.9324, 0.3991],
         [0.6103, 0.3761, 0.8970,  ..., 0.1341, 0.4927, 0.2721]],

        [[0.7871, 0.9248, 0.4622,  ..., 0.8196, 0.0152, 0.5638],
         [0.2310, 0.5822, 0.2027,  ..., 0.6749, 0.4712, 0.0078],
         [0.8241, 0.7803, 0.1790,  ..., 0.7991, 0.7484, 0.3185],
         ...,
         [0.3649, 0.5789, 0.2976,  ..., 0.5109, 0.5095, 0.6978],
         [0.5050, 0.4666, 0.8696,  ..., 0.7384, 0.3527, 0.1292],
         [0.2942, 0.2622, 0.6345,  ..., 0.8201, 0.2135, 0.6822]],

        [[0.4784, 0.0749, 0.9893,  ..., 0.5031, 0.8829, 0.3531],
         [0.2357, 0.6974, 0.6230,  ..., 0.3095, 0.3359, 0.0963],
         [0.7924, 0.0507, 0.4924,  ..., 0.6009, 0.8867, 0.

In [22]:
tensore_rand2.ndim , tensore_rand2.shape

(3, torch.Size([3, 224, 224]))

## zeros or ones arrays useed often to mask biger arrays

In [23]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
aranges=torch.arange(1,11,1)
aranges

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
zeros_like=torch.zeros_like(input=aranges)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch
& deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor*float_32_tensor ## why this work?

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor=torch.tensor([1,2,3],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
float_16_tensor*int_32_tensor

tensor([ 3., 12., 27.], dtype=torch.float16)

In [32]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.6581, 0.2271, 0.9844, 0.4664],
        [0.9351, 0.3675, 0.0837, 0.7338],
        [0.3667, 0.4722, 0.1421, 0.6756]])

In [33]:
print(some_tensor)
print(f"this is the dtype of tensor: {some_tensor.dtype}")
print(f"this is the shape of tenosr: {some_tensor.shape}")
print(f"this is the device of tensor: {some_tensor.device}")

tensor([[0.6581, 0.2271, 0.9844, 0.4664],
        [0.9351, 0.3675, 0.0837, 0.7338],
        [0.3667, 0.4722, 0.1421, 0.6756]])
this is the dtype of tensor: torch.float32
this is the shape of tenosr: torch.Size([3, 4])
this is the device of tensor: cpu


##math in tensors

In [34]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [35]:
tensor+10

tensor([11, 12, 13])

In [36]:
tensor*10

tensor([10, 20, 30])

In [37]:
tensor-10

tensor([-9, -8, -7])

In [38]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutliplication (dot product)
More information on multiplying matrices -  https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [39]:
%%time
torch.matmul(tensor,tensor)
## since the total time is 10 time or more less than for loop this method is too better

CPU times: user 230 µs, sys: 1.05 ms, total: 1.28 ms
Wall time: 15.7 ms


tensor(14)

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 538 µs, sys: 765 µs, total: 1.3 ms
Wall time: 1.56 ms


* short cut for torch.matmul is @
1. the first rule in matrxt multiblication is the inner dimintion should be equla
- for example:
* '(3,2)'@'(3,2)' not work
* '(3,2)'@'(2,3)' will work
* '(2,3)'@'(3,2)' will work
2. the resultin is the outer dimintion

In [41]:
(torch.rand(3,2) @ torch.rand(2,3) ).shape

torch.Size([3, 3])

#the transpose is importatint how to use it

In [42]:
tensor=torch.rand(3,2)
tensor

tensor([[0.0118, 0.6669],
        [0.6816, 0.4462],
        [0.3887, 0.6731]])

In [43]:
tensor @ tensor.T

tensor([[0.4449, 0.3057, 0.4535],
        [0.3057, 0.6637, 0.5653],
        [0.4535, 0.5653, 0.6042]])

In [44]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [46]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [47]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [49]:
x.argmax()

tensor(9)

In [50]:
x.argmin()

tensor(0)

##Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
View
* Return a view of an input tensor of certain shape but keep the same memory as the original tensor
Stacking
* combine multiple tensors on top of each other (vstack) or side by side (hstack)
Squeeze
* removes all 1 dimensions from a tensor
Unsqueeze
* add a 1 dimension to a target tensor
Permute
* Return a view of the input with dimensions permuted (swapped) in a certain way

In [51]:
tensor=torch.arange(1,10)
tensor,tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [52]:
tensor_reshape=tensor.reshape(1,9)
tensor_reshape,tensor_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [53]:
tensor_reshape=tensor.reshape(3,3)
tensor_reshape,tensor_reshape.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [54]:
tensor , tensor_reshape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [55]:
tensor[0]=66
tensor , tensor_reshape

(tensor([66,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[66,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

In [56]:
x=torch.arange(1,10)
x ,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [57]:
z=x.view(3,3)
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
x[0]=55
x,z
#reshape and view do the same

(tensor([55,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[55,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

**contiguous memore** : "each row follows the previous one directly in memory"
* view : contiguous it work fine but if not not work
* reshape : if not contiguous it rearnge it and work fine.

**then what make tensor not contiguous ??**

In [59]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
x = torch.stack((a, b))
x,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

the .stack() functions add two tensore together
* but using dim attribute behave like: "where the index of new diminshin will be"

  and this shape how the output will be

In [60]:
x = torch.stack((a, b),dim=0)
x,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [61]:
x = torch.stack((a, b),dim=1)
x,x.shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

### try higher diminshions

In [62]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
d = torch.randn(2, 3)
print(f"The stack when dim is 0 :\n{torch.stack((a, b, d), dim=0)}")
print(f"The shpae of stack when The dim is 0 :\n{torch.stack((a, b, d), dim=0).shape}")
print("************************************************************************************************")
print(f"The stack when dim is 1 :\n{torch.stack((a, b, d), dim=1)}")
print(f"The shpae of stack when The dim is 1 :\n{torch.stack((a, b, d), dim=1).shape}")
print("************************************************************************************************")
print(f"The stack when dim is 2 :\n{torch.stack((a, b, d), dim=2)}")
print(f"The shpae of stack when The dim is 2 :\n{torch.stack((a, b, d), dim=2).shape}")
## the dim = 3 cuse error

The stack when dim is 0 :
tensor([[[ 0.1350,  0.8696,  0.3536],
         [-0.2692, -0.5747,  0.0524]],

        [[ 1.4977, -0.3021, -0.7952],
         [-1.9307, -0.2103, -1.6042]],

        [[ 1.5348, -2.0596,  0.0401],
         [-0.2737, -0.8442, -1.2611]]])
The shpae of stack when The dim is 0 :
torch.Size([3, 2, 3])
************************************************************************************************
The stack when dim is 1 :
tensor([[[ 0.1350,  0.8696,  0.3536],
         [ 1.4977, -0.3021, -0.7952],
         [ 1.5348, -2.0596,  0.0401]],

        [[-0.2692, -0.5747,  0.0524],
         [-1.9307, -0.2103, -1.6042],
         [-0.2737, -0.8442, -1.2611]]])
The shpae of stack when The dim is 1 :
torch.Size([2, 3, 3])
************************************************************************************************
The stack when dim is 2 :
tensor([[[ 0.1350,  1.4977,  1.5348],
         [ 0.8696, -0.3021, -2.0596],
         [ 0.3536, -0.7952,  0.0401]],

        [[-0.2692, -1.93

###the squeeze tensors

In [63]:
tensor=torch.arange(1,10).reshape(1,9)
tensor, tensor.shape

print(f"the tensore before squezze:{tensor}")
print(f"the shape before squezze:{tensor.shape}")
print("************************************************************************************************")
print(f"the tensore after squezze:{tensor.squeeze()}")
print(f"the shape after squezze:{tensor.squeeze().shape}")

the tensore before squezze:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
the shape before squezze:torch.Size([1, 9])
************************************************************************************************
the tensore after squezze:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
the shape after squezze:torch.Size([9])
