<a href="https://colab.research.google.com/github/MD2001/Pytorch_Bignnier/blob/main/00_pytoirch_first_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Title: 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Discussion forum: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## introduction
### tensors

In [4]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.shape

torch.Size([])

In [6]:
scaler.ndim

0

In [7]:
#Vector
Vector=torch.tensor([7,7])
Vector

tensor([7, 7])

In [8]:
Vector.shape

torch.Size([2])

In [9]:
Vector.ndim

1

In [10]:
#MATRIX
MATRIX =torch.tensor([[1,3],[2,4]])
MATRIX

tensor([[1, 3],
        [2, 4]])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([1, 3])

In [14]:
MATRIX[1]

tensor([2, 4])

In [15]:
#Tensors
TENSOR = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 4])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [19]:
Tesnor2=torch.tensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
Tesnor2

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [20]:
Tesnor2.ndim

3

In [21]:
Tesnor2.shape

torch.Size([2, 3, 2])

## Random tensors
### Why random tensors?
### Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then
### Torch random tensors-https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [22]:
tensore_rand=torch.rand(3,4)
tensore_rand

tensor([[0.0115, 0.1458, 0.9407, 0.6447],
        [0.7050, 0.7829, 0.0122, 0.4209],
        [0.0439, 0.0042, 0.6193, 0.8707]])

In [23]:
tensore_rand2=torch.rand(size=(3,224,224))
tensore_rand2

tensor([[[9.0127e-03, 4.6912e-02, 6.7591e-01,  ..., 1.4989e-01,
          1.4851e-01, 6.5810e-01],
         [3.3050e-01, 2.4828e-01, 6.3569e-01,  ..., 1.6010e-01,
          5.0105e-01, 1.5899e-02],
         [1.6753e-01, 1.5654e-01, 3.1923e-01,  ..., 2.6369e-01,
          4.6691e-01, 3.9161e-02],
         ...,
         [8.4726e-01, 7.9292e-01, 8.3101e-01,  ..., 1.6136e-01,
          2.3324e-01, 4.7410e-01],
         [8.3770e-02, 9.5213e-01, 4.9229e-01,  ..., 8.9702e-02,
          4.1616e-01, 9.5996e-01],
         [4.8863e-01, 7.4798e-01, 9.5838e-01,  ..., 8.9036e-01,
          2.7049e-01, 9.6068e-01]],

        [[1.9921e-01, 9.7602e-01, 9.1667e-01,  ..., 4.4841e-01,
          5.8582e-01, 2.8442e-01],
         [4.7001e-01, 9.0934e-02, 3.7043e-01,  ..., 4.8218e-01,
          8.5646e-01, 9.2041e-01],
         [7.9901e-01, 9.6905e-02, 4.6343e-01,  ..., 8.8784e-01,
          1.5399e-01, 1.0514e-01],
         ...,
         [6.3521e-01, 2.8354e-01, 4.2030e-01,  ..., 5.7530e-04,
          2.707

In [24]:
tensore_rand2.ndim , tensore_rand2.shape

(3, torch.Size([3, 224, 224]))

## zeros or ones arrays useed often to mask biger arrays

In [25]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
aranges=torch.arange(1,11,1)
aranges

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
zeros_like=torch.zeros_like(input=aranges)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch
& deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [29]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor ## why this work?

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor=torch.tensor([1,2,3],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
float_16_tensor*int_32_tensor

tensor([ 3., 12., 27.], dtype=torch.float16)

In [34]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4812, 0.7332, 0.2066, 0.3211],
        [0.0142, 0.4409, 0.6979, 0.4678],
        [0.6839, 0.2751, 0.2230, 0.6850]])

In [35]:
print(some_tensor)
print(f"this is the dtype of tensor: {some_tensor.dtype}")
print(f"this is the shape of tenosr: {some_tensor.shape}")
print(f"this is the device of tensor: {some_tensor.device}")

tensor([[0.4812, 0.7332, 0.2066, 0.3211],
        [0.0142, 0.4409, 0.6979, 0.4678],
        [0.6839, 0.2751, 0.2230, 0.6850]])
this is the dtype of tensor: torch.float32
this is the shape of tenosr: torch.Size([3, 4])
this is the device of tensor: cpu


##math in tensors

In [36]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [37]:
tensor+10

tensor([11, 12, 13])

In [38]:
tensor*10

tensor([10, 20, 30])

In [39]:
tensor-10

tensor([-9, -8, -7])

In [40]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutliplication (dot product)
More information on multiplying matrices -  https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [41]:
%%time
torch.matmul(tensor,tensor)
## since the total time is 10 time or more less than for loop this method is too better

CPU times: user 1.27 ms, sys: 39 µs, total: 1.31 ms
Wall time: 14 ms


tensor(14)

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.31 ms, sys: 0 ns, total: 1.31 ms
Wall time: 1.75 ms


* short cut for torch.matmul is @
1. the first rule in matrxt multiblication is the inner dimintion should be equla
- for example:
* '(3,2)'@'(3,2)' not work
* '(3,2)'@'(2,3)' will work
* '(2,3)'@'(3,2)' will work
2. the resultin is the outer dimintion

In [43]:
(torch.rand(3,2) @ torch.rand(2,3) ).shape

torch.Size([3, 3])

#the transpose is importatint how to use it

In [44]:
tensor=torch.rand(3,2)
tensor

tensor([[0.0997, 0.4081],
        [0.1328, 0.1536],
        [0.7177, 0.1222]])

In [45]:
tensor @ tensor.T

tensor([[0.1765, 0.0759, 0.1215],
        [0.0759, 0.0412, 0.1141],
        [0.1215, 0.1141, 0.5301]])

In [46]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [48]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [49]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [50]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [51]:
x.argmax()

tensor(9)

In [52]:
x.argmin()

tensor(0)

##Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
View
* Return a view of an input tensor of certain shape but keep the same memory as the original tensor
Stacking
* combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze removes all 1 dimensions from a tensor

* Unsqueeze add a 1 dimension to a target tensor

* Permute Return a view of the input with dimensions permuted (swapped) in a certain way

In [53]:
tensor=torch.arange(1,10)
tensor,tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [54]:
tensor_reshape=tensor.reshape(1,9)
tensor_reshape,tensor_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [55]:
tensor_reshape=tensor.reshape(3,3)
tensor_reshape,tensor_reshape.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [56]:
tensor , tensor_reshape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [57]:
tensor[0]=66
tensor , tensor_reshape

(tensor([66,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[66,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

In [58]:
x=torch.arange(1,10)
x ,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [59]:
z=x.view(3,3)
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
x[0]=55
x,z
#reshape and view do the same

(tensor([55,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[55,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

**contiguous memore** : "each row follows the previous one directly in memory"
* view : contiguous it work fine but if not not work
* reshape : if not contiguous it rearnge it and work fine.

**then what make tensor not contiguous ??**

In [61]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
x = torch.stack((a, b))
x,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

the .stack() functions add two tensore together
* but using dim attribute behave like: "where the index of new diminshin will be"

  and this shape how the output will be

In [62]:
x = torch.stack((a, b),dim=0)
x,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [63]:
x = torch.stack((a, b),dim=1)
x,x.shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

### try higher diminshions

In [64]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
d = torch.randn(2, 3)
print(f"The stack when dim is 0 :\n{torch.stack((a, b, d), dim=0)}")
print(f"The shpae of stack when The dim is 0 :\n{torch.stack((a, b, d), dim=0).shape}")
print("************************************************************************************************")
print(f"The stack when dim is 1 :\n{torch.stack((a, b, d), dim=1)}")
print(f"The shpae of stack when The dim is 1 :\n{torch.stack((a, b, d), dim=1).shape}")
print("************************************************************************************************")
print(f"The stack when dim is 2 :\n{torch.stack((a, b, d), dim=2)}")
print(f"The shpae of stack when The dim is 2 :\n{torch.stack((a, b, d), dim=2).shape}")
## the dim = 3 cuse error

The stack when dim is 0 :
tensor([[[-0.6085,  0.5635, -0.1615],
         [-2.4490,  0.7763,  0.1091]],

        [[-0.2544, -0.6590,  0.1214],
         [-0.1328, -0.9848,  0.4930]],

        [[-0.4603, -1.1238, -1.3459],
         [-1.1426,  2.0416, -0.0734]]])
The shpae of stack when The dim is 0 :
torch.Size([3, 2, 3])
************************************************************************************************
The stack when dim is 1 :
tensor([[[-0.6085,  0.5635, -0.1615],
         [-0.2544, -0.6590,  0.1214],
         [-0.4603, -1.1238, -1.3459]],

        [[-2.4490,  0.7763,  0.1091],
         [-0.1328, -0.9848,  0.4930],
         [-1.1426,  2.0416, -0.0734]]])
The shpae of stack when The dim is 1 :
torch.Size([2, 3, 3])
************************************************************************************************
The stack when dim is 2 :
tensor([[[-0.6085, -0.2544, -0.4603],
         [ 0.5635, -0.6590, -1.1238],
         [-0.1615,  0.1214, -1.3459]],

        [[-2.4490, -0.13

###the squeeze tensors

In [65]:
tensor=torch.arange(1,10).reshape(1,9)
tensor, tensor.shape

print(f"the tensore before squezze:{tensor}")
print(f"the shape before squezze:{tensor.shape}")
print("************************************************************************************************")
print(f"the tensore after squezze:{tensor.squeeze()}")
print(f"the shape after squezze:{tensor.squeeze().shape}")

the tensore before squezze:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
the shape before squezze:torch.Size([1, 9])
************************************************************************************************
the tensore after squezze:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
the shape after squezze:torch.Size([9])


In [66]:
tensor=torch.arange(1,10)
tensor, tensor.shape

print(f"the tensore before unsquezze:{tensor}")
print(f"the shape before unsquezze:{tensor.shape}")
print("************************************************************************************************")
print(f"the tensore after unsquezze dim = 0:{tensor.unsqueeze(dim=0)}")
print(f"the shape after unsquezze dim = 0:{tensor.unsqueeze(dim=0).shape}")
print("************************************************************************************************")
print(f"the tensore after unsquezze dim = 1:{tensor.unsqueeze(dim=1)}")
print(f"the shape after unsquezze dim = 1:{tensor.unsqueeze(dim=1).shape}")

the tensore before unsquezze:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
the shape before unsquezze:torch.Size([9])
************************************************************************************************
the tensore after unsquezze dim = 0:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
the shape after unsquezze dim = 0:torch.Size([1, 9])
************************************************************************************************
the tensore after unsquezze dim = 1:tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
the shape after unsquezze dim = 1:torch.Size([9, 1])


In [67]:
orginal_tensor=torch.rand(size=(5,6,7))
tranc_tensor=orginal_tensor.permute(2,0,1)
print(f"orginal_tensor shape:{orginal_tensor.shape}")
print(f"trans_tensor shape:{tranc_tensor.shape}")
print(f"orginal_tensor shape:{orginal_tensor.shape}")
## poth share the same memory but have diffrent view
print(f"the index on orginal tensor:{orginal_tensor[0,0,0]}")
print(f"the index on trans_tensor:{tranc_tensor[0,0,0]}")
orginal_tensor[0,0,0]=2
print(f"the index on orginal tensor after change:{orginal_tensor[0,0,0]}")
print(f"the index on trans_tensor after change:{tranc_tensor[0,0,0]}")



orginal_tensor shape:torch.Size([5, 6, 7])
trans_tensor shape:torch.Size([7, 5, 6])
orginal_tensor shape:torch.Size([5, 6, 7])
the index on orginal tensor:0.42161720991134644
the index on trans_tensor:0.42161720991134644
the index on orginal tensor after change:2.0
the index on trans_tensor after change:2.0


# indexing

In [68]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
x[0][0]

tensor([1, 2, 3])

In [71]:
#seperte [n][n][n] is equal to [n,n,n]
x[0,0,0]

tensor(1)

In [72]:
# we use : to say select all elemnt in this diminshine
x[:,0]

tensor([[1, 2, 3]])

In [73]:
new=torch.arange(11,20).reshape(1,3,3)
x=torch.cat((x,new),dim=0)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [74]:
x[:,0]

tensor([[ 1,  2,  3],
        [11, 12, 13]])

In [75]:
x[:,0,2]

tensor([ 3, 13])

## get start from numpy to tensor

In [76]:
import numpy as np
array=np.arange(1,8)
tensor=torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [77]:
## every time you run this line you get differant tensor
rand_tensor=torch.rand(3,4)
rand_tensor


tensor([[0.3942, 0.1374, 0.5976, 0.2256],
        [0.5905, 0.5207, 0.5304, 0.7588],
        [0.1247, 0.4710, 0.7195, 0.4448]])

In [78]:
## always get the same set of number
torch.manual_seed(42)
rand_tensor=torch.rand(3,4)
rand_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [79]:
!nvidia-smi ## do it after reasigne the runtime hardware to gpu

Tue Oct 28 11:00:14 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [81]:
torch.cuda.is_available()

True

In [82]:
torch.cuda.device_count()

1