<a href="https://colab.research.google.com/github/MD2001/Pytorch_Bignnier/blob/main/00_pytoirch_first_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Title: 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Discussion forum: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## introduction
### tensors

In [2]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.shape

torch.Size([])

In [4]:
scaler.ndim

0

In [5]:
#Vector
Vector=torch.tensor([7,7])
Vector

tensor([7, 7])

In [6]:
Vector.shape

torch.Size([2])

In [7]:
Vector.ndim

1

In [8]:
#MATRIX
MATRIX =torch.tensor([[1,3],[2,4]])
MATRIX

tensor([[1, 3],
        [2, 4]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([1, 3])

In [12]:
MATRIX[1]

tensor([2, 4])

In [13]:
#Tensors
TENSOR = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 4])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [17]:
Tesnor2=torch.tensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
Tesnor2

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [18]:
Tesnor2.ndim

3

In [19]:
Tesnor2.shape

torch.Size([2, 3, 2])

## Random tensors
### Why random tensors?
### Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then
### Torch random tensors-https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
tensore_rand=torch.rand(3,4)
tensore_rand

tensor([[0.4246, 0.0741, 0.2301, 0.4343],
        [0.0805, 0.5112, 0.6793, 0.3658],
        [0.8298, 0.5581, 0.9291, 0.9069]])

In [21]:
tensore_rand2=torch.rand(size=(3,224,224))
tensore_rand2

tensor([[[0.5958, 0.3872, 0.1113,  ..., 0.2802, 0.2286, 0.5099],
         [0.0621, 0.8834, 0.1815,  ..., 0.7163, 0.5119, 0.7412],
         [0.7458, 0.8984, 0.3680,  ..., 0.7286, 0.2338, 0.0485],
         ...,
         [0.9801, 0.8495, 0.5946,  ..., 0.4536, 0.1558, 0.9258],
         [0.5503, 0.0490, 0.8151,  ..., 0.6480, 0.0651, 0.0039],
         [0.4763, 0.7346, 0.0514,  ..., 0.1454, 0.2568, 0.1449]],

        [[0.4094, 0.8203, 0.4544,  ..., 0.0801, 0.8554, 0.7827],
         [0.6153, 0.3635, 0.2886,  ..., 0.2304, 0.7643, 0.3136],
         [0.0838, 0.9243, 0.0287,  ..., 0.4509, 0.9922, 0.9324],
         ...,
         [0.6215, 0.3525, 0.6980,  ..., 0.0158, 0.0760, 0.2569],
         [0.5284, 0.4768, 0.3821,  ..., 0.0971, 0.2260, 0.2630],
         [0.5345, 0.8454, 0.6555,  ..., 0.8591, 0.2705, 0.5058]],

        [[0.8678, 0.3187, 0.5386,  ..., 0.7938, 0.8558, 0.4755],
         [0.4527, 0.2376, 0.5579,  ..., 0.8789, 0.9538, 0.5292],
         [0.7935, 0.5739, 0.4434,  ..., 0.5309, 0.4255, 0.

In [22]:
tensore_rand2.ndim , tensore_rand2.shape

(3, torch.Size([3, 224, 224]))

## zeros or ones arrays useed often to mask biger arrays

In [23]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
aranges=torch.arange(1,11,1)
aranges

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
zeros_like=torch.zeros_like(input=aranges)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch
& deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor*float_32_tensor ## why this work?

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor=torch.tensor([1,2,3],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
float_16_tensor*int_32_tensor

tensor([ 3., 12., 27.], dtype=torch.float16)

In [32]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.2235, 0.2705, 0.7323, 0.7114],
        [0.6024, 0.0729, 0.0480, 0.4144],
        [0.8322, 0.0618, 0.8275, 0.8111]])

In [33]:
print(some_tensor)
print(f"this is the dtype of tensor: {some_tensor.dtype}")
print(f"this is the shape of tenosr: {some_tensor.shape}")
print(f"this is the device of tensor: {some_tensor.device}")

tensor([[0.2235, 0.2705, 0.7323, 0.7114],
        [0.6024, 0.0729, 0.0480, 0.4144],
        [0.8322, 0.0618, 0.8275, 0.8111]])
this is the dtype of tensor: torch.float32
this is the shape of tenosr: torch.Size([3, 4])
this is the device of tensor: cpu


##math in tensors

In [34]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [35]:
tensor+10

tensor([11, 12, 13])

In [36]:
tensor*10

tensor([10, 20, 30])

In [37]:
tensor-10

tensor([-9, -8, -7])

In [38]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutliplication (dot product)
More information on multiplying matrices -  https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [39]:
%%time
torch.matmul(tensor,tensor)
## since the total time is 10 time or more less than for loop this method is too better

CPU times: user 742 µs, sys: 0 ns, total: 742 µs
Wall time: 13.2 ms


tensor(14)

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.29 ms, sys: 914 µs, total: 2.21 ms
Wall time: 2.47 ms


* short cut for torch.matmul is @
1. the first rule in matrxt multiblication is the inner dimintion should be equla
- for example:
* '(3,2)'@'(3,2)' not work
* '(3,2)'@'(2,3)' will work
* '(2,3)'@'(3,2)' will work
2. the resultin is the outer dimintion

In [41]:
(torch.rand(3,2) @ torch.rand(2,3) ).shape

torch.Size([3, 3])

#the transpose is importatint how to use it

In [42]:
tensor=torch.rand(3,2)
tensor

tensor([[0.8453, 0.9532],
        [0.5906, 0.9629],
        [0.6374, 0.1191]])

In [43]:
tensor @ tensor.T

tensor([[1.6232, 1.4171, 0.6523],
        [1.4171, 1.2759, 0.4911],
        [0.6523, 0.4911, 0.4204]])

In [44]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [46]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [47]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [49]:
x.argmax()

tensor(9)

In [50]:
x.argmin()

tensor(0)

##Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
View
* Return a view of an input tensor of certain shape but keep the same memory as the original tensor
Stacking
* combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze removes all 1 dimensions from a tensor

* Unsqueeze add a 1 dimension to a target tensor

* Permute Return a view of the input with dimensions permuted (swapped) in a certain way

In [51]:
tensor=torch.arange(1,10)
tensor,tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [52]:
tensor_reshape=tensor.reshape(1,9)
tensor_reshape,tensor_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [53]:
tensor_reshape=tensor.reshape(3,3)
tensor_reshape,tensor_reshape.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [54]:
tensor , tensor_reshape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [55]:
tensor[0]=66
tensor , tensor_reshape

(tensor([66,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[66,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

In [56]:
x=torch.arange(1,10)
x ,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [57]:
z=x.view(3,3)
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
x[0]=55
x,z
#reshape and view do the same

(tensor([55,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[55,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

**contiguous memore** : "each row follows the previous one directly in memory"
* view : contiguous it work fine but if not not work
* reshape : if not contiguous it rearnge it and work fine.

**then what make tensor not contiguous ??**

In [59]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
x = torch.stack((a, b))
x,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

the .stack() functions add two tensore together
* but using dim attribute behave like: "where the index of new diminshin will be"

  and this shape how the output will be

In [60]:
x = torch.stack((a, b),dim=0)
x,x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [61]:
x = torch.stack((a, b),dim=1)
x,x.shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

### try higher diminshions

In [62]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
d = torch.randn(2, 3)
print(f"The stack when dim is 0 :\n{torch.stack((a, b, d), dim=0)}")
print(f"The shpae of stack when The dim is 0 :\n{torch.stack((a, b, d), dim=0).shape}")
print("************************************************************************************************")
print(f"The stack when dim is 1 :\n{torch.stack((a, b, d), dim=1)}")
print(f"The shpae of stack when The dim is 1 :\n{torch.stack((a, b, d), dim=1).shape}")
print("************************************************************************************************")
print(f"The stack when dim is 2 :\n{torch.stack((a, b, d), dim=2)}")
print(f"The shpae of stack when The dim is 2 :\n{torch.stack((a, b, d), dim=2).shape}")
## the dim = 3 cuse error

The stack when dim is 0 :
tensor([[[ 0.3097, -0.4222,  0.4748],
         [-2.4333,  1.8548,  1.5133]],

        [[-0.9410, -0.6206,  1.5652],
         [ 0.4664, -2.0762, -1.6407]],

        [[-0.8835,  1.4499,  0.6416],
         [ 0.0332, -0.5398,  0.7937]]])
The shpae of stack when The dim is 0 :
torch.Size([3, 2, 3])
************************************************************************************************
The stack when dim is 1 :
tensor([[[ 0.3097, -0.4222,  0.4748],
         [-0.9410, -0.6206,  1.5652],
         [-0.8835,  1.4499,  0.6416]],

        [[-2.4333,  1.8548,  1.5133],
         [ 0.4664, -2.0762, -1.6407],
         [ 0.0332, -0.5398,  0.7937]]])
The shpae of stack when The dim is 1 :
torch.Size([2, 3, 3])
************************************************************************************************
The stack when dim is 2 :
tensor([[[ 0.3097, -0.9410, -0.8835],
         [-0.4222, -0.6206,  1.4499],
         [ 0.4748,  1.5652,  0.6416]],

        [[-2.4333,  0.46

###the squeeze tensors

In [63]:
tensor=torch.arange(1,10).reshape(1,9)
tensor, tensor.shape

print(f"the tensore before squezze:{tensor}")
print(f"the shape before squezze:{tensor.shape}")
print("************************************************************************************************")
print(f"the tensore after squezze:{tensor.squeeze()}")
print(f"the shape after squezze:{tensor.squeeze().shape}")

the tensore before squezze:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
the shape before squezze:torch.Size([1, 9])
************************************************************************************************
the tensore after squezze:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
the shape after squezze:torch.Size([9])


In [64]:
tensor=torch.arange(1,10)
tensor, tensor.shape

print(f"the tensore before unsquezze:{tensor}")
print(f"the shape before unsquezze:{tensor.shape}")
print("************************************************************************************************")
print(f"the tensore after unsquezze dim = 0:{tensor.unsqueeze(dim=0)}")
print(f"the shape after unsquezze dim = 0:{tensor.unsqueeze(dim=0).shape}")
print("************************************************************************************************")
print(f"the tensore after unsquezze dim = 1:{tensor.unsqueeze(dim=1)}")
print(f"the shape after unsquezze dim = 1:{tensor.unsqueeze(dim=1).shape}")

the tensore before unsquezze:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
the shape before unsquezze:torch.Size([9])
************************************************************************************************
the tensore after unsquezze dim = 0:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
the shape after unsquezze dim = 0:torch.Size([1, 9])
************************************************************************************************
the tensore after unsquezze dim = 1:tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
the shape after unsquezze dim = 1:torch.Size([9, 1])


In [65]:
orginal_tensor=torch.rand(size=(5,6,7))
tranc_tensor=orginal_tensor.permute(2,0,1)
print(f"orginal_tensor shape:{orginal_tensor.shape}")
print(f"trans_tensor shape:{tranc_tensor.shape}")
print(f"orginal_tensor shape:{orginal_tensor.shape}")
## poth share the same memory but have diffrent view
print(f"the index on orginal tensor:{orginal_tensor[0,0,0]}")
print(f"the index on trans_tensor:{tranc_tensor[0,0,0]}")
orginal_tensor[0,0,0]=2
print(f"the index on orginal tensor after change:{orginal_tensor[0,0,0]}")
print(f"the index on trans_tensor after change:{tranc_tensor[0,0,0]}")



orginal_tensor shape:torch.Size([5, 6, 7])
trans_tensor shape:torch.Size([7, 5, 6])
orginal_tensor shape:torch.Size([5, 6, 7])
the index on orginal tensor:0.6841785311698914
the index on trans_tensor:0.6841785311698914
the index on orginal tensor after change:2.0
the index on trans_tensor after change:2.0


# indexing

In [67]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [68]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [69]:
x[0][0]

tensor([1, 2, 3])

In [72]:
#seperte [n][n][n] is equal to [n,n,n]
x[0,0,0]

tensor(1)

In [73]:
# we use : to say select all elemnt in this diminshine
x[:,0]

tensor([[1, 2, 3]])

In [78]:
new=torch.arange(11,20).reshape(1,3,3)
x=torch.cat((x,new),dim=0)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [79]:
x[:,0]

tensor([[ 1,  2,  3],
        [11, 12, 13]])

In [87]:
x[:,0,2]

tensor([ 3, 13])

## get start from numpy to tensor

In [90]:
import numpy as np
array=np.arange(1,8)
tensor=torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))